name: Stock

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'feature**'
    paths:
      - 'stock-microservice/**' 
  delete:
    branches:
      - 'feature**'

env:
  SAM_TEMPLATE: ./stock-microservice/template.yml
  DEVELOPMENT_STACK_NAME: stock-microservice-stack-development
  PROD_STACK_NAME: stock-microservice-stack-quality

permissions:
  id-token: write
  contents: read

jobs:

  delete-feature:
    if: startsWith(github.event.ref, 'feature') && github.event_name == 'delete'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume the development pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.DEVELOPMENT_REGION }}
          role-to-assume: ${{ vars.DEVELOPMENT_PIPELINE_EXECUTION_ROLE }}
          role-session-name: development-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Delete feature branch stack
        env:
          FEATURE_BRANCH_NAME: ${{ github.event.ref }}
        run: |
          sam delete \
            --stack-name $(echo ${FEATURE_BRANCH_NAME} | tr '/' '-') \
            --region ${{vars.DEVELOPMENT_REGION}} \
            --no-prompts

  build-and-deploy-feature:
    if: startsWith(github.ref, 'refs/heads/feature')
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - run: sam build --template ${SAM_TEMPLATE} --use-container --mount-with WRITE
      - name: Assume the development pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.DEVELOPMENT_REGION }}
          role-to-assume: ${{ vars.DEVELOPMENT_PIPELINE_EXECUTION_ROLE }}
          role-session-name: feature-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to feature stack in the development account
        shell: bash
        run: |
          sam deploy --stack-name $(echo ${GITHUB_REF_NAME} | tr '/' '-') \
            --capabilities CAPABILITY_IAM \
            --region ${{vars.DEVELOPMENT_REGION}} \
            --s3-bucket ${{vars.DEVELOPMENT_ARTIFACTS_BUCKET}} \
            --no-fail-on-empty-changeset \
            --role-arn ${{vars.DEVELOPMENT_CLOUDFORMATION_EXECUTION_ROLE}} \
            --parameter-overrides TagEnvironment=$(echo ${GITHUB_REF_NAME} | tr '/' '-') \
                HostedZoneId=Z00743383VXA4QAJRZZWR \
                LambdaAuthorizerArn=${{vars.LAMBDA_AUTHORIZER_ARN}} \
                CertificateArn=arn:aws:acm:us-east-1:968225077300:certificate/05afa741-7893-4f67-901f-e70f43ba9704


  build-and-deploy-development:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - uses: actions/checkout@v3

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume the development pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.DEVELOPMENT_REGION }}
          role-to-assume: ${{ vars.DEVELOPMENT_PIPELINE_EXECUTION_ROLE }}
          role-session-name: development-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - run: sam build --template ${SAM_TEMPLATE} --use-container --mount-with WRITE
      - name: Upload artifacts to development artifact buckets
        run: |
          sam package \
            --s3-bucket ${{vars.DEVELOPMENT_ARTIFACTS_BUCKET}} \
            --region ${{ vars.DEVELOPMENT_REGION }} \
            --output-template-file packaged-development.yaml

      - name: Deploy to development account
        run: |
          sam deploy --stack-name ${DEVELOPMENT_STACK_NAME} \
            --template packaged-development.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${{ vars.DEVELOPMENT_REGION }} \
            --s3-bucket ${{vars.DEVELOPMENT_ARTIFACTS_BUCKET}} \
            --no-fail-on-empty-changeset \
            --role-arn ${{vars.DEVELOPMENT_CLOUDFORMATION_EXECUTION_ROLE}} \
            --parameter-overrides TagEnvironment=development \
                HostedZoneId=Z00743383VXA4QAJRZZWR \
                LambdaAuthorizerArn=${{vars.LAMBDA_AUTHORIZER_ARN}} \
                CertificateArn=arn:aws:acm:us-east-1:968225077300:certificate/05afa741-7893-4f67-901f-e70f43ba9704

  build-and-deploy-production:
    if: github.ref == 'refs/heads/main'
    needs: [build-and-deploy-development]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Assume the prod pipeline user role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ vars.PROD_REGION }}
          role-to-assume: ${{ vars.PROD_PIPELINE_EXECUTION_ROLE }}
          role-session-name: prod-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - run: sam build --template ${SAM_TEMPLATE} --use-container --mount-with WRITE
      - name: Upload artifacts to prod artifact buckets
        run: |
          sam package \
            --s3-bucket ${{vars.PROD_ARTIFACTS_BUCKET}} \
            --region ${{ vars.PROD_REGION }} \
            --output-template-file packaged-prod.yaml

      - name: Deploy to production account
        run: |
          sam deploy --stack-name ${PROD_STACK_NAME} \
            --template packaged-prod.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${PROD_REGION} \
            --s3-bucket ${{vars.PROD_ARTIFACTS_BUCKET}} \
            --no-fail-on-empty-changeset \
            --role-arn ${PROD_CLOUDFORMATION_EXECUTION_ROLE} \
            --parameter-overrides TagEnvironment=production \
                HostedZoneId=Z00743383VXA4QAJRZZWR \
                LambdaAuthorizerArn=${{vars.LAMBDA_AUTHORIZER_ARN}} \
                CertificateArn=arn:aws:acm:us-east-1:968225077300:certificate/05afa741-7893-4f67-901f-e70f43ba9704

